"""
Chat Engine — post-report conversational AI.

Maintains report context in memory so the user can ask follow-up
questions like "Why was account X flagged?" or "What does structuring mean?"
"""
from __future__ import annotations

import json
import textwrap

from inference.llm_engine import llm_engine


_CHAT_SYSTEM = textwrap.dedent("""
    You are a helpful financial fraud analysis assistant. The user has just
    received a fraud risk report generated by an AI system. Your job is to:

    1. Answer questions about specific accounts in the report.
    2. Explain fraud typologies in plain English.
    3. Help the user understand what action to take.
    4. Be concise, clear, and professional.
    5. Never fabricate data — only use the report context provided.
    6. Never start responses with "As an AI..." or "I am an AI...". Speak directly and confidently as the system analyst.

    Keep responses under 150 words unless the user asks for more detail.
""").strip()


async def chat(
    user_message: str,
    report_summary: dict,
    conversation_history: list[dict],
) -> str:
    """
    Generate a conversational response about the fraud report.

    Args:
        user_message: The user's question.
        report_summary: The full report dict from the job result.
        conversation_history: List of {role, content} dicts (last 6 turns).

    Returns:
        str: The assistant's reply.
    """
    # Build context from report
    report_context = _summarize_report_for_context(report_summary)

    # Build conversation history string
    history_str = ""
    for turn in conversation_history[-6:]:
        role = "user" if turn.get("role") == "user" else "assistant"
        history_str += f"<|im_start|>{role}\n{turn.get('content', '')}<|im_end|>\n"

    prompt = textwrap.dedent(f"""
        <|im_start|>system
        {_CHAT_SYSTEM}

        REPORT CONTEXT:
        {report_context}<|im_end|>
        {history_str}<|im_start|>user
        {user_message}<|im_end|>
        <|im_start|>assistant
    """).strip()

    response = await llm_engine.generate(prompt, max_new_tokens=300, temperature=0.5)

    # Clean up if LLM returned the structured verdict format accidentally
    if response.startswith("VERDICT:"):
        response = (
            "Based on the report, I can see this account has elevated risk indicators. "
            "Could you ask a more specific question about the findings?"
        )

    return response.strip()


def _summarize_report_for_context(report: dict) -> str:
    """Convert the report dict into a compact text summary for the prompt."""
    if not report:
        return "No report data available."

    overview = report.get("overview", {})
    accounts = report.get("flagged_accounts", [])[:10]  # Top 10 for context

    lines = [
        f"File: {report.get('filename', 'unknown')}",
        f"Total transactions: {overview.get('total_transactions', '?')}",
        f"Total accounts: {overview.get('total_accounts', '?')}",
        f"Fraud rate: {overview.get('fraud_percentage', 0):.1f}%",
        f"High-risk accounts: {overview.get('high_risk_count', 0)}",
        "",
        "Top flagged accounts:",
    ]

    for acct in accounts:
        reasons = ", ".join(acct.get("top_reasons", [])) or "None specified"
        analysis = acct.get("analysis", "No analysis available")
        lines.append(
            f"  - Account {acct.get('account_id')}: "
            f"{acct.get('verdict', '?')} risk ({acct.get('confidence', 0)}% confidence), "
            f"action={acct.get('action', '?')}, "
            f"flagged {acct.get('flagged_txn_count', 0)}/{acct.get('total_txn_count', 0)} txns.\n"
            f"    Reasons: {reasons}\n"
            f"    Analysis: {analysis}"
        )

    return "\n".join(lines)
